### PR TITLE
WIP: Mobile table of contents

### LINKED ISSUE #35: Make sure TOC is visible on low resolutions
Now TOC is hidden on low resolutions. Not ideal.

### PR DESCRIPTION
**Pull request by sapegin**
Fixes #35.

screen recording 2018-02-12 at 09 46 pm

### CODE REVIEW

**Comment by bebraw** [comment]
Great start. 👍

**Comment by sapegin** [comment]
Anything you’d like to change?

**Comment by bebraw** [comment]
Maybe a slower close animation but even now it looks nice.

**Comment by sapegin** [comment]
I need to test that on a real device to see if any adjustments are needed, GIF isn’t the best way to test animations ;-)

**Comment by sapegin** [comment]
I've tweaked animations a bit (also on hamburger: had the same issue on closing), and cleaned up code.

**Comment by sapegin** [comment]
Could you checkout the branch and see if that's good enough? ;-)

**Comment by bebraw** [comment]
Looks great. Merged.

**Comment by st-sloth** [comment]
This is awesome! Thank you!

**Pull request merged**
