### PR TITLE
Try Emotion

### PR DESCRIPTION
**Pull request by sapegin**
I’m still trying to understand how to make styles extraction work ;-/

### CODE REVIEW

**Comment by bebraw** [comment]
It might be easier to test this against [the simple demo at antwar repository](https://github.com/antwarjs/antwar/tree/master/smoketest). I wonder if the build process works against style extraction here. It generates a big site bundle before generating individual pages.

**Comment by sapegin** [comment]
The problem is it doesn’t work with *dynamic* styles, so even `${t.space.xl}` doesn’t work. I need to investigate what option we have.

**Comment by bebraw** [comment]
Ah, right. They suggest using CSS variables for dynamic bits.

**Comment by sapegin** [comment]
But they are not dynamic from the run time point of view ;-) I guess we can make another plugin to inline theme variables. Another problem is props — we’ll probably have to split these components into multiple.

**Comment by sapegin** [comment]
Now I need to solve the modifiers issue (` <Panel prev>`, `<Panel next>`).

**Comment by sapegin** [comment]
@bebraw How do you like it now? Static extraction works fine as long as you don’t use any dynamic content like functions. But you may use `theme`.

**Comment by sapegin** [comment]
I guess it’s done and works quite well. What do you think?

**Comment by bebraw** [comment]
Really nice work. I think eventually we should push components like this to https://github.com/survivejs-sites/components and implement a style guide. Nice, isolated, and reusable.

**Comment by sapegin** [comment]
Yeah, that wood be good ;-)

**Pull request merged**
